description: Customer table
display_name: 'Dbt: Source: Jaffle Shop: Customers'
type: source
columns:
  id:
    type: INT
  first_name:
    type: STR
  last_name:
    type: STR
tables:
  postgres:
  - catalog: null
    schema: jaffle_shop
    table: customers
    cost: 10.0
