description: Country level agg table
type: transform
query: |
  SELECT country, 
    -- COUNT(1) as num_comments, 
    COUNT(DISTINCT id) as num_users
  FROM basic.source.users 
   -- AS a, basic.dimension.comments ON user_id = basic.dimension.users.id 
   GROUP BY country
columns:
  country:
    type: STR
  num_users:
    type: INT
