description: User dimension
type: dimension
query: SELECT * FROM basic.source.users
columns:
  id:
    type: FLOAT
  full_name:
    type: STR
  age:
    type: FLOAT
  country:
    type: STR
  gender:
    type: STR
  preferred_language:
    type: STR
  secret_number:
    type: FLOAT
