name: Update and Commit OpenAPI Spec
on: [workflow_dispatch]
jobs:
  update-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install DJ
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate OpenAPI Spec
        run: ./scripts/generate-openapi.py -o openapi.json

      - name: Commit Updated OpenAPI Spec
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update OpenAPI Spec
          file_pattern: 'openapi.json'
